#!/usr/bin/env bash
# Usage: sub pm search [package name]
# Summary: Search known repositories for sub-modules
# Help: This command searches all the repositories listed in libexec/sub-pm/repos.conf for sub-modules

set -e

shift 

SEARCH="$1"

DNULL="$(sub pm search update)"

_SUB_REPOS_DIR="$_SUB_COMMAND_ROOT/cache/repos"
_SUB_REPOS_PATH="$_SUB_REPOS_DIR/repos.conf"

while read line           
do          
	if [ "$line" == "" ]; then
		continue
	fi

	IFS=':' read -ra ADDR <<< "$line"
	_SUB_TEMP_REPO_OWNER="${ADDR[1]}"

	IFS='/' read -ra ADDR <<< "$_SUB_TEMP_REPO_OWNER"
	_SUB_REPO_OWNER="${ADDR[0]}"
	_SUB_REPO="$(echo ${ADDR[1]} | sed 's|.git||g')"

	_SUB_LINE_DIR="$(echo $line | sed 's|[^A-Za-z0-9]||g')"
	_SUB_LINE_PATH="$_SUB_COMMAND_ROOT/cache/$_SUB_LINE_DIR"

    if [ ! -d "$_SUB_LINE_PATH" ]; then
    	mkdir -p $_SUB_LINE_PATH
		git clone $line $_SUB_LINE_PATH
	fi

	cd $_SUB_LINE_PATH
	
#	if [ older than one day then]; then
#		git pull >> /dev/null
#    fi

    BRANCHES="$(git branch -a)"
    BRANCHES="$(echo $BRANCHES | sed 's|remotes/origin/master||g' | sed 's|remotes/origin/HEAD -> origin/master||g' | sed 's|. master||g')"
    BRANCHES=($BRANCHES)
    declare -a PACKAGES

    echo ""
    echo -e "\tsub package manager v0.1"
    echo ""
    echo ""
    echo -e "    [package name]\t[package summary]"
    echo ""

	for branch in "${BRANCHES[@]}"; do
		branch="$(echo $branch  | sed 's|remotes/origin/||g')"
		if [[ "$branch" == *$SEARCH* ]]; then
			if [[ "$branch" == mod_* ]]; then
				_SUB_BRANCH="$branch"
				_SUB_SUMMARY_FILE="$(echo $_SUB_BRANCH | sed 's|mod_||g')"
				_SUB_GH_PACKAGE_URL="https://raw.github.com/$_SUB_REPO_OWNER/$_SUB_REPO/$_SUB_BRANCH/$_SUB_SUMMARY_FILE"
				_SUB_BRANCH_SUMMARY="$(curl -s $_SUB_GH_PACKAGE_URL | awk '/^[^#]/{p=0} /^# Help:/{p=1} p' | sed 's/^# Help: //;s/^# /\\t\\t\\t/;s/^#/\\n\\t\\t\\t/')" # " | grep '# Summary:' | sed 's|<[^>]*>||g' | sed 's|# Summary:||g' | sed 's/^ *//g')"
				package="$(echo $_SUB_BRANCH | sed 's|mod_||g' | sed 's|-| |g')"
				PACKAGES[${#PACKAGES}]="$branch"
				echo -e "    $package: \t$_SUB_BRANCH_SUMMARY"
				echo ""
				echo -e "\t\t\tsub pm install $branch"
				echo ""
			elif [[ "$package" == plugin_* ]]; then 
				echo "Found Plugin"
			fi
		fi
	done

	echo ""
	echo ""
done < "$_SUB_REPOS_PATH"
